"""Write the Python SOP's code: the engine followed by the Houdini glue, as one self-contained file.

    python houdini/build_sop.py   ->  houdini/ringloom_sop.py

Paste ringloom_sop.py into a Python SOP's Code parameter (or let Claude set it through the
Houdini MCP). Embedding it means a saved .hip keeps working without this repo.
"""
import os

here = os.path.dirname(os.path.abspath(__file__))
engine = open(os.path.join(here, "ringloom_engine.py"), encoding="utf-8").read()
glue = open(os.path.join(here, "sop_glue.py"), encoding="utf-8").read()
header = "# GENERATED by houdini/build_sop.py from ringloom_engine.py + sop_glue.py -- edit those, not this.\n"
out = os.path.join(here, "ringloom_sop.py")
with open(out, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(header + engine + "\n\n" + glue)
print("wrote %s (%d lines)" % (out, (header + engine + glue).count("\n")))
