"""Refresh the engine embedded in an existing Ring Loom scene, keeping everything else in it.

    hython houdini/update_hip_code.py path/to/scene.hip [more.hip ...]

Every Python SOP whose code carries this repo's "GENERATED by houdini/build_sop.py" header gets
the current houdini/ringloom_sop.py. Before saving, each updated SOP is checked: it is pointed at a
temporary two-look sequence using the newest view and sequence settings (roll, yaw, pitch,
perspective, extra roll turns, stagger, swirl), sampled mid-blend, and its geometry must match the
engine run directly. Cameras driven by the SOP get its current camera expressions (including the
orthographic switch) and must see the rings as the page does, in perspective and orthographic.
The SOP's own file setting is restored afterwards. A scene is saved only if every check passes;
otherwise it is left untouched on disk.

Use this instead of make_example_hip.py when a scene has extra work in it (render setup, your own
nodes) that a rebuild would lose.
"""
import json
import os
import sys
import tempfile

import hou
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ringloom_engine as E  # noqa: E402

MARKER = "GENERATED by houdini/build_sop.py"
code = open(os.path.join(HERE, "ringloom_sop.py"), encoding="utf-8").read()

# Two looks with different rolls, sampled a quarter of the way through a blend that adds an extra
# roll turn, so the check covers the newest view and sequence features, not just one still look.
# The newest generators and base shape ride along: Hopf fibration on one side, Pendulum wave on an
# odd lopsided Superformula (drawn over two turns) on the other, Spirograph in the ortho probe.
probe_a = dict(E.DEFAULTS, gen="hopf", roll=63.0, yaw=-28.0, pitch=17.0, persp=0.5, rings=9, res=64)
# Different palettes, so the colour mixing (OKLCH, with out-of-range colours pulled toward grey)
# is checked too, not only positions.
# Its view differs too (yaw, pitch, spin), so the 3D view blend is covered.
probe_b = dict(E.DEFAULTS, gen="pendulum", base="super", sfM=5, sfN1=1.3, sfN2=3.0, sfN3=8.0, roll=-40.0, yaw=35.0, pitch=-10.0, spin=25.0, persp=0.5, rings=6, res=64,
               palette="acid" if E.DEFAULTS["palette"] != "acid" else "ember")
probe_cards = [{"name": "probe a", "params": probe_a, "hold": 0.5, "blend": 2, "ease": "linear", "turns": 1,
                "stagger": 0.5, "swirl": 200},
               {"name": "probe b", "params": probe_b, "hold": 1, "blend": 1}]
fd, probe_path = tempfile.mkstemp(suffix=".ringloom.json")
with os.fdopen(fd, "w", encoding="utf-8") as fh:
    json.dump({"ringLoom": 1, "kind": "sequence", "name": "probe", "sequence": probe_cards}, fh)
# Perspective 0: the page is orthographic, and so must the camera be.
ortho_look = dict(E.DEFAULTS, gen="spiro", spMode="epi", yaw=30.0, pitch=25.0, persp=0.0, rings=7, res=64)
fd, ortho_path = tempfile.mkstemp(suffix=".ringloom.json")
with os.fdopen(fd, "w", encoding="utf-8") as fh:
    json.dump({"ringLoom": 1, "kind": "look", "name": "ortho probe", "params": ortho_look,
               "sequence": [{"name": "ortho probe", "params": ortho_look}]}, fh)


def update_cameras(sop):
    """Cameras driven by this SOP (their distance reads cam_distance from its output) get every
    expression in E.CAMERA_EXPRESSIONS -- projection, ortho width and far clip came with the
    orthographic view -- then are checked against the page's projection with a perspective probe
    (mid-blend) and an orthographic one. Returns a list of (camera, message, ok)."""
    results = []
    for cam in hou.node("/obj").allSubChildren():
        if cam.type().name() != "cam" or cam.parm("tz") is None:
            continue
        try:
            expr = cam.parm("tz").expression()
        except hou.OperationFailed:
            continue
        if "cam_distance" not in expr:
            continue
        src = hou.node(expr.split('"')[1]) if '"' in expr else None
        if src is None or not (src == sop or sop in src.inputAncestors()):
            continue
        for parm, attrib in E.CAMERA_EXPRESSIONS:
            cam.parm(parm).setExpression(expr.replace("cam_distance", attrib))
        file_parm = sop.parm("file")
        old_raw = file_parm.unexpandedString()
        look = sop.parm("look").eval() if sop.parm("look") else 0
        if look:
            sop.parm("look").set(0)
        errs = []
        for path, cards, label in ((probe_path, probe_cards, "perspective"), (ortho_path, [{"name": "o", "params": ortho_look}], "orthographic")):
            file_parm.set(path.replace("\\", "/"))
            hou.setFrame(sop.evalParm("start_frame") + 24)
            src.cook(force=True)
            frame, _ = E.evaluate([E.clean_card(c) for c in cards], 24 / sop.evalParm("fps"))
            res = sop.evalParm("render_res")
            P = np.array(src.geometry().pointFloatAttribValues("P")).reshape(-1, 3)[: frame["pre"].shape[0] * frame["pre"].shape[1]]
            ortho = cam.evalParm("projection") == 1
            got = E.camera_projection(P, cam.evalParm("tz"), cam.evalParm("focal"), cam.evalParm("aperture"),
                                      ortho, cam.evalParm("orthowidth"), res)
            err = float(np.max(np.abs(got - E.project(frame, res).reshape(-1, 2))))
            want_ortho = label == "orthographic"
            errs.append((label, err, ortho == want_ortho))
        file_parm.set(old_raw)
        if look:
            sop.parm("look").set(look)
        ok = all(e < 1e-3 and right for _, e, right in errs)
        results.append((cam, "; ".join("%s %s, %.1e px" % (l, "ok" if r else "WRONG PROJECTION", e) for l, e, r in errs), ok))
    return results

failed = False
for hip in sys.argv[1:]:
    hou.hipFile.load(hip, suppress_save_prompt=True, ignore_load_warnings=True)
    sops = [n for n in hou.node("/").allSubChildren()
            if n.type().name() == "python" and MARKER in (n.parm("python").eval() if n.parm("python") else "")]
    if not sops:
        print("%s: no Ring Loom SOP found, nothing changed" % hip)
        continue
    ok = True
    for sop in sops:
        sop.parm("python").set(code)
        file_parm = sop.parm("file")
        old_raw = file_parm.unexpandedString()
        file_parm.set(probe_path.replace("\\", "/"))
        look = sop.parm("look").eval() if sop.parm("look") else 0
        if look:
            sop.parm("look").set(0)
        hou.setFrame(sop.evalParm("start_frame") + 24)
        sop.cook(force=True)
        errs = sop.errors()
        P = np.array(sop.geometry().pointFloatAttribValues("P")).reshape(-1, 3)
        clock = 24 / sop.evalParm("fps")
        frame, label = E.evaluate([E.clean_card(c) for c in probe_cards], clock)
        assert "->" in label, "probe time should fall inside the blend, got %r" % label
        rings = E.world_rings(frame)
        want = np.concatenate([r[0] for r in rings]) * sop.evalParm("scale")
        err = float(np.max(np.abs(P - want))) if P.shape == want.shape else float("inf")
        Cd = np.array(sop.geometry().primFloatAttribValues("Cd")).reshape(-1, 3)
        want_cd = np.array([r[1] for r in rings])
        cd_err = float(np.max(np.abs(Cd - want_cd))) if Cd.shape == want_cd.shape else float("inf")
        colour_spread = float(np.ptp(want_cd, axis=0).max())  # proof the probe really mixes colours
        file_parm.set(old_raw)
        if look:
            sop.parm("look").set(look)
        status = "ok" if not errs and err < 1e-5 and cd_err < 1e-5 and colour_spread > 0.05 else "FAILED"
        ok = ok and status == "ok"
        print("%s: %s updated, rolled blend check %s (max error: points %.1e, colours %.1e)%s"
              % (hip, sop.path(), status, err, cd_err, "; errors: %s" % (errs,) if errs else ""))
        for cam, msg, cam_ok in update_cameras(sop):
            ok = ok and cam_ok
            print("%s: camera %s updated, view against the page: %s" % (hip, cam.path(), msg))
    if ok:
        hou.hipFile.save(hip)
        print("%s: saved" % hip)
    else:
        failed = True
        print("%s: NOT saved" % hip)

os.remove(probe_path)
os.remove(ortho_path)
sys.exit(1 if failed else 0)
