"""Refresh the engine embedded in an existing Ring Loom scene, keeping everything else in it.

    hython houdini/update_hip_code.py path/to/scene.hip [more.hip ...]

Every Python SOP whose code carries this repo's "GENERATED by houdini/build_sop.py" header gets
the current houdini/ringloom_sop.py. Before saving, each updated SOP is checked: it is pointed at a
temporary look that uses the newest view settings (roll, yaw, pitch, perspective) and its geometry
must match the engine run directly. The SOP's own file setting is restored afterwards. A scene is
saved only if every check passes; otherwise it is left untouched on disk.

Use this instead of make_example_hip.py when a scene has extra work in it (render setup, your own
nodes) that a rebuild would lose.
"""
import json
import os
import sys
import tempfile

import hou
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ringloom_engine as E  # noqa: E402

MARKER = "GENERATED by houdini/build_sop.py"
code = open(os.path.join(HERE, "ringloom_sop.py"), encoding="utf-8").read()

probe = dict(E.DEFAULTS, gen="sphere", roll=63.0, yaw=-28.0, pitch=17.0, persp=0.5, rings=9, res=64)
fd, probe_path = tempfile.mkstemp(suffix=".ringloom.json")
with os.fdopen(fd, "w", encoding="utf-8") as fh:
    json.dump({"ringLoom": 1, "kind": "look", "name": "probe", "params": probe,
               "sequence": [{"name": "probe", "params": probe}]}, fh)

failed = False
for hip in sys.argv[1:]:
    hou.hipFile.load(hip, suppress_save_prompt=True, ignore_load_warnings=True)
    sops = [n for n in hou.node("/").allSubChildren()
            if n.type().name() == "python" and MARKER in (n.parm("python").eval() if n.parm("python") else "")]
    if not sops:
        print("%s: no Ring Loom SOP found, nothing changed" % hip)
        continue
    ok = True
    for sop in sops:
        sop.parm("python").set(code)
        file_parm = sop.parm("file")
        old_raw = file_parm.unexpandedString()
        file_parm.set(probe_path.replace("\\", "/"))
        look = sop.parm("look").eval() if sop.parm("look") else 0
        if look:
            sop.parm("look").set(0)
        hou.setFrame(sop.evalParm("start_frame") + 24)
        sop.cook(force=True)
        errs = sop.errors()
        P = np.array(sop.geometry().pointFloatAttribValues("P")).reshape(-1, 3)
        clock = 24 / sop.evalParm("fps")
        frame, _ = E.evaluate([E.clean_card({"name": "probe", "params": probe})], clock)
        want = np.concatenate([r[0] for r in E.world_rings(frame)]) * sop.evalParm("scale")
        err = float(np.max(np.abs(P - want))) if P.shape == want.shape else float("inf")
        file_parm.set(old_raw)
        if look:
            sop.parm("look").set(look)
        status = "ok" if not errs and err < 1e-5 else "FAILED"
        ok = ok and status == "ok"
        print("%s: %s updated, rolled-view check %s (max error %.1e)%s"
              % (hip, sop.path(), status, err, "; errors: %s" % (errs,) if errs else ""))
    if ok:
        hou.hipFile.save(hip)
        print("%s: saved" % hip)
    else:
        failed = True
        print("%s: NOT saved" % hip)

os.remove(probe_path)
sys.exit(1 if failed else 0)
